### ISSUE TITLE
Add README.md

### ISSUE THREAD

**Issue by leethax666** [retsamknaps/Aktie#17]
What exactly is this project? I'm an I2P fan.

**Comment by retsamknaps** [comment]
Yes this will be nice when done.  Sorry it is not yet.  We also want to use the github web pages.

**Comment by kigerpunk** [comment]
I'd be willing to help if I knew exactly what it did. As it is, I don't even know enough to help with docs.

**Comment by retsamknaps** [comment]
That would be great.  Aktie is a way for people to share files and messages in communities.  Anyone can create a community.  They can be private or public, or semi-private.  Public communities anyone can participate.  Private communities are hidden from everyone except members.  The creator of a private community can grant others membership.  Semi-private or "Locked" communities are private communities except the name and creator of the community anyone can see.  To participate in a community you must subscribe to it.  You can subscribe to any public community or any private/locked community you are a member of.  Once subscribed you can post messages, add files, link posts to files, add previews, etc to the community.  Files can be downloaded from a community, and aktie will download much like bittorrent in that it will download fragments of the file from as many others as possible.  So if more people have a file the faster it will download.  Aktie can also be searched very quickly.  All files and posts are indexed locally so search is very fast.

To be useful though Aktie must be kept running.  When people add a file to a community it is not "pushed" anywhere.  It is just made available for others to download from you.  If you add a file then turn aktie off, no one will be able to get the file.  Once many people have downloaded a file though it will be more available, assuming at least one person has their node on.

Aktie uses I2P to protect anonymity of those participating.  It will try to use an existing I2P router if you already have one running, or it will automatically start an embedded router if not.

Please feel free to fork and make a README.md then submit us a pull request if you would like.

**Comment by kigerpunk** [comment]
Is there a difference between this and BitTorrent (particularly with private trackers or peer exchange) other than the use of I2P?

**Comment by aaannndddyyy** [comment]
@ke7ofi to me this is more like a distributed forum.
In bittorrent you share only files. 
Here you have diffreten forums, called communiteis - public forums and private forums. 
And you write messages to those communities, just like posts on a forum, just that there is no server where the forum is hosted. 
And you can share files in these forums/communites. 
For big files I think bt is better, because it optimises how parts are spread. 
But here you can communicate with your friends, colleagues, likeminded, ... in a secure and anonymous way, and also share some smaller files. It's p2p

bittorrent can also be be serverless, if you use DHT and PEX. But you still need a place where to geth the magnet links from.
you cna share those in aktie too.
